### ISSUE TITLE
Add imperative API

### ISSUE THREAD

**Issue by bdice** [glotzerlab/plato#2]
**[Original report](https://bitbucket.org/glotzer/plato/issue/2) by Matthew Spellings (Bitbucket: [mspells](https://bitbucket.org/mspells), GitHub: [klarh](https://github.com/klarh)).**

----------------------------------------

Something like how matplotlib's API works in notebooks would possibly be really handy to replicate by having a set of functions that are working on a single scene object at once. Something vaguely like:

```
import plato.imperative as imp

# automatically set diameters to 1?
imp.spheres(positions=[...], colors=[...])
other_shapes = imp.convex_polyhedra(positions=[...], orientations=[...])
other_shapes.colors[:, 1] = 1

# automatically pick a backend
imp.show()
# alternatively, select a backend
imp.show(backend='povray')

# either of those show commands will make future imp commands work on a fresh new scene
imp.polygons(...)
imp.show(backend='matplotlib')
```

This would likely be done using an IPython callback, as described in [the IPython documentation](https://ipython.readthedocs.io/en/stable/config/callbacks.html).

**Comment by klarh** [comment]
Added in cd6e6aa39837228289488ff4bf4d2520fcfb311f
