### ISSUE TITLE
Adjustable number of vertices for pythreejs Spheres

### ISSUE THREAD

**Issue by bdice** [glotzerlab/plato#24]
https://github.com/glotzerlab/plato/blob/1b006c1dced4cd270aaf17893e588d214826296f/plato/draw/pythreejs/Spheres.py#L22-L23

@alacour and I have been manually setting this value much, much higher for our renderings with pythreejs. @klarh I'd like to make a PR, do you have advice on how to improve this?

**Comment by klarh** [comment]
It should be straightforward to add as an attribute using mechanisms similar to what we have [in other backends](https://github.com/glotzerlab/plato/blob/1b006c1dced4cd270aaf17893e588d214826296f/plato/draw/povray/ConvexPolyhedra.py#L10-L17). Then it's just a matter of using the value of that attribute (maybe named `vertex_count`?) in this line.
