### ISSUE TITLE
Add caps to Lines

### ISSUE THREAD

**Issue by bdice** [glotzerlab/plato#3]
**[Original report](https://bitbucket.org/glotzer/plato/issue/3) by Matthew Spellings (Bitbucket: [mspells](https://bitbucket.org/mspells), GitHub: [klarh](https://github.com/klarh)).**

----------------------------------------

This should be a relatively straightforward matter of extending lines a bit past the end and maybe adding a few lines to the fragment shader for one of the styles.

Proposed cap types:

- none: current behavior (default)
- flat: extend by some ratio of the line width past the end
- round: extend by width/2 past the end and round the cap in the fragment shader

**Comment by klarh** [comment]
Fixed as of ebf9bd028d0935b04391b14410e5bcc17e9d9f1f.
