### ISSUE TITLE
Add ellipsoids

### ISSUE THREAD

**Issue by bdice** [glotzerlab/plato#4]
**[Original report](https://bitbucket.org/glotzer/plato/issue/4) by Matthew Spellings (Bitbucket: [mspells](https://bitbucket.org/mspells), GitHub: [klarh](https://github.com/klarh)).**

----------------------------------------

Unclear whether this is best done in opengl with a single triangle and lots of overdraw (like Disks and Spheres work now) or with a cube.

**Comment by klarh** [comment]
Fixed by PR #29
